version: '3.7'

services:
  bot:
    build: 
      context: bot
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - DEBUG=False
    networks:
      - bot-network
    

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - ./mongodb/data:/data/db
    networks:
      - bot-network


networks:
  bot-network:
    driver: bridge